### ISSUE TITLE
Check for minimum java version and provide a reasonable error

### ISSUE THREAD

**Issue by cbeer** [projecthydra/jettywrapper#43]
Recent versions of Solr require Java 7+. We should provide a way to somehow require a minimum java  version (in the jetty.yml file?) and raise an appropriate error otherwise.

**Comment by awead** [comment]
Linux and Mac systems could do a system call, ex. `java -version` to get an idea, but I'm not sure what we could do for windows systems. Any ideas, @cbeer ?
