### ISSUE TITLE
Not able to specify the hydra-jetty version from the command line

### ISSUE THREAD

**Issue by mark-dce** [projecthydra/jettywrapper#51]
I'm trying to run my application with a specific version of hydra-jetty, but when I try to specify a release on the command line, I'm still getting the current master downloaded.  I'm assuming this is some kind of pilot error, but I'm not sure what.  I'm trying to follow the pattern here: [Configuring jettywrapper](https://github.com/projecthydra/jettywrapper/wiki/Configuring-jettywrapper#other-jettys)

```
$ JETTY_ZIP="https://github.com/projecthydra/hydra-jetty/archive/v8.3.1.zip" rake jetty:download
I, [2015-10-27T10:30:27.623066 #24568]  INFO -- : Downloading jetty at https://github.com/projecthydra/hydra-jetty/archive/master.zip ...
```
i.e. it's downloading "master", not the specific release I'm trying to get.

**Comment by jcoyne** [comment]
You are trying to set an environment variable. This is not something that jettywrapper supports. You can set JETTY_ZIP as a constant in the Rakefile, then it should work.
